spring.application.name=Test
server.address=0.0.0.0
server.port=8000

# Logiciels nécessaires
java_package=openjdk-17-jdk
maven_package=maven
git_package=git

# Ports
port_preprod=8000
port_prod=9000


# Ports à tester pour le projet Spring Boot
port_start=8000
port_end=9000